#port: 6123
ip: 192.168.123.254/24
dhcp-range: 192.168.123.100-192.168.123.200
bridge: br0
#log-level: info
key: B5FFCEE73EF298A4
routes:
  - cidr: 192.168.0.0/24
    nexthop: SERVER # route nexthop to virtuallan server
  - cidr: 192.168.1.0/24
    nexthop: wj # route nexthop user name
  - cidr: 192.168.2.0/24
    nexthop: guest # route nexthop user name
web:
  enable: true
  port: 8000