name: Build virtullan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod tidy

    - name: Run build
      run: make

